[project]
name = "Telegram-Channel-to-QQ"
version = "1.0.0"
description = "Telegram-Channel-to-QQ 是一个 Telegram 频道消息同步转发到 QQ 群的机器人，支持文本、链接和图片媒体消息的转发。"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    # required by lottie[gif]
    "aiosqlite>=0.22.1",
    "cairosvg>=2.8.2",
    # tg 表情转 gif
    "lottie[gif]>=0.7.2",
    "python-dotenv>=1.1.0",
    # tg webm 动画和 sticker 转 gif
    "python-ffmpeg>=2.0.12",
    "python-telegram-bot>=22.0",
    "websockets>=15.0.1",
]
